services:
  tyro-nginx:
    image: ghcr.io/tyroai/tyro-nginx/tyro-nginx:main
    container_name: tyro-nginx
    ports:
      - "8000:80"
    depends_on:
      - tyro-backend-api
      - tyro-frontend
    networks:
      - tyro-network
    restart: unless-stopped

  tyro-backend-api:
    image: ghcr.io/tyroai/tyro-backend-api/tyro-backend-api:main
    container_name: tyro-backend-api
    networks:
      - tyro-network
    restart: unless-stopped
    env_file:
      - ./configs/.env

  tyro-frontend:
    image: ghcr.io/tyroai/tyro-frontend/tyro-frontend:main
    container_name: tyro-frontend
    networks:
      - tyro-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tyro-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - tyro-network

  mongo:
    image: mongodb/mongodb-atlas-local
    container_name: tyro-mongo
    volumes:
      - mongo-datavv:/data/db
      # Time synchronization
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - ./configs/.env
    ports:
      - "27017:27017"
    networks:
      - tyro-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: tyro-minio
    volumes:
      - minio-data:/data
      # Time synchronization
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - ./configs/.env
    networks:
      - tyro-network
    ports:
      - "9001:9001"
      - "9000:9000"

networks:
  tyro-network:

volumes:
  mongo-datavv:
  minio-data:
  redis_data: