version: "3.9"

services:
  mongo:
    image: mongodb/mongodb-atlas-local
    container_name: tyro-mongo
    volumes:
      - mongo-data:/data/
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - ./configs/.env
    ports:
      - "27018:27017"
    networks:
      - tyro-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  temporal-postgresql:
    image: postgres:12
    container_name: tyro-temporal-postgresql
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"
    networks:
      - tyro-network
    volumes:
      - temporal-postgresql-data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.28.1
    container_name: tyro-temporal
    depends_on:
      - temporal-postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=tyro-temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=tyro-temporal:7233
      - TEMPORAL_CLI_ADDRESS=tyro-temporal:7233
    networks:
      - tyro-network
    volumes:
      - ./configs:/etc/temporal/config/dynamicconfig

  minio:
    image: minio/minio:latest
    container_name: tyro-minio
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - tyro-network
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - ./configs/.env

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=tyro-temporal:7233
      - TEMPORAL_CLI_ADDRESS=tyro-temporal:7233
    image: temporalio/admin-tools:1.28.1-tctl-1.18.4-cli-1.4.1
    networks:
      - tyro-network
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=tyro-temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.34.0
    networks:
      - tyro-network
    ports:
      - 8001:8080

networks:
  tyro-network:

volumes:
  mongo-data:
  minio-data:
  temporal-postgresql-data:
  mongo-data-config: